import { useEffect, useState } from 'react'
import { AnimatePresence, motion, useMotionValue, useScroll, useSpring, useTransform } from 'framer-motion'
import { Swiper, SwiperSlide } from 'swiper/react'
import { Autoplay } from 'swiper/modules'
import Lightbox from 'yet-another-react-lightbox'
import Zoom from 'yet-another-react-lightbox/plugins/zoom'
import { FiArrowRight, FiArrowUpRight, FiMenu, FiPhone, FiPlay, FiX } from 'react-icons/fi'
import { FaWhatsapp } from 'react-icons/fa'
import { collections } from '../data/collections'
import { fabricGallery } from '../data/fabricGallery'
import { galleryImages } from '../data/gallery'
import { videos } from '../data/videos'
import { VideoModal } from '../components/sections/VideoCollectionSection'
import 'swiper/css'
import 'yet-another-react-lightbox/styles.css'
import './CatalogPage.css'

const phone = '+91 9601419809'
const call = `tel:${phone.replace(/\s/g, '')}`
const whatsapp = `https://wa.me/${phone.replace(/\D/g, '')}`
const logo = `${import.meta.env.BASE_URL}Screenshot 2026-07-15 183312.png`
const go = (id) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' })
const reveal = { hidden: { opacity: 0, y: 28, scale: .985, filter: 'blur(8px)' }, show: { opacity: 1, y: 0, scale: 1, filter: 'blur(0px)', transition: { duration: .72, ease: [0.22, 1, 0.36, 1] } } }
const stagger = { hidden: {}, show: { transition: { staggerChildren: .1, delayChildren: .04 } } }

function Magnetic({ children, className, ...props }) { const x = useMotionValue(0); const y = useMotionValue(0); const springX = useSpring(x, { stiffness: 180, damping: 14, mass: .2 }); const springY = useSpring(y, { stiffness: 180, damping: 14, mass: .2 }); const move = (event) => { const rect = event.currentTarget.getBoundingClientRect(); x.set((event.clientX - rect.left - rect.width / 2) * .12); y.set((event.clientY - rect.top - rect.height / 2) * .12) }; return <motion.div className={className} style={{ x: springX, y: springY }} onPointerMove={move} onPointerLeave={() => { x.set(0); y.set(0) }} {...props}>{children}</motion.div> }
function ScrollProgress() { const { scrollYProgress } = useScroll(); const scaleX = useSpring(scrollYProgress, { stiffness: 120, damping: 30, restDelta: .001 }); return <motion.div className="scroll-progress" style={{ scaleX }} /> }

function Preloader() { const [visible, setVisible] = useState(true); useEffect(() => { const timer = setTimeout(() => setVisible(false), 1150); return () => clearTimeout(timer) }, []); return <AnimatePresence>{visible && <motion.div className="preloader" initial={{ opacity: 1 }} exit={{ opacity: 0, scale: 1.03, filter: 'blur(4px)', transition: { duration: .55, ease: [0.22, 1, 0.36, 1] } }}><motion.img src={logo} alt="VESTIORA" initial={{ opacity: 0, scale: .88, filter: 'blur(8px)' }} animate={{ opacity: 1, scale: [1, 1.035, 1], filter: 'blur(0px)' }} transition={{ duration: .8, times: [0, .6, 1] }} /><motion.span className="loader-line" initial={{ scaleX: 0 }} animate={{ scaleX: 1 }} transition={{ duration: .85, ease: [0.22, 1, 0.36, 1] }} /></motion.div>}</AnimatePresence> }

function Nav({ onHome }) { const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const links = [['Home', 'home'], ['Collections', 'collections'], ['Market Journey', 'market-journey'], ['Contact', 'contact']]; useEffect(() => { const update = () => setScrolled(window.scrollY > 12); update(); window.addEventListener('scroll', update, { passive: true }); return () => window.removeEventListener('scroll', update) }, []); const navigate = (id) => { onHome(); setTimeout(() => go(id), 0) }; return <motion.header className={`nav ${scrolled ? 'nav-scrolled' : ''}`} initial={{ y: -24, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ duration: .6, ease: [0.22, 1, 0.36, 1] }}><motion.button className="brand reset" onClick={onHome} aria-label="VESTIORA home" whileHover={{ scale: 1.025 }} whileTap={{ scale: .98 }}><img src={logo} alt="VESTIORA" style={{ height: '50px', width: 'auto', display: 'block' }} /></motion.button><nav>{links.map(([label, id]) => <button onClick={() => navigate(id)} key={id}>{label}</button>)}</nav><motion.a className="nav-call" href={call} whileHover={{ y: -2, scale: 1.02 }} whileTap={{ scale: .98 }}><FiPhone /> Call</motion.a><button className="menu reset" onClick={() => setOpen(!open)}>{open ? <FiX /> : <FiMenu />}</button><AnimatePresence>{open && <motion.div className="mobile-nav" initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}>{links.map(([label, id]) => <button onClick={() => { setOpen(false); navigate(id) }} key={id}>{label}</button>)}</motion.div>}</AnimatePresence></motion.header> }

function Hero() { const { scrollY } = useScroll(); const imageY = useTransform(scrollY, [0, 800], [0, 72]); const copyY = useTransform(scrollY, [0, 800], [0, -28]); return <section id="home" className="hero"><motion.div className="hero-copy" style={{ y: copyY }}><motion.p className="eyebrow" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .55 }}>VESTIORA · SURAT</motion.p><motion.h1 initial="hidden" animate="show" variants={stagger}><motion.span variants={reveal} className="hero-line">Kurta fabrics,</motion.span><motion.em variants={reveal} className="hero-line">considered.</motion.em></motion.h1><motion.p className="hero-text" initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .28, duration: .6 }}>A refined digital catalogue of premium kurta fabrics — selected for texture, colour and exceptional finish.</motion.p><Magnetic className="magnetic-button"><motion.button className="button" initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .38, duration: .55 }} whileHover={{ scale: 1.025 }} whileTap={{ scale: .97 }} onClick={() => go('collections')}>View Collections <FiArrowRight /><i /></motion.button></Magnetic></motion.div><motion.div className="hero-slider" style={{ y: imageY }} initial={{ opacity: 0, scale: .97, clipPath: 'inset(0 0 100% 0)' }} animate={{ opacity: 1, scale: 1, clipPath: 'inset(0 0 0% 0)' }} transition={{ duration: .95, ease: [0.22, 1, 0.36, 1] }}><Swiper modules={[Autoplay]} autoplay={{ delay: 3500, disableOnInteraction: false }} loop slidesPerView={1} className="hero-swiper">{collections.slice(0, 4).map((item) => <SwiperSlide key={item.id}><img src={item.cover} alt={`${item.name} kurta fabric`} /><div><p>PREMIUM KURTA FABRIC</p><h2>{item.name}</h2></div></SwiperSlide>)}</Swiper></motion.div></section> }

function Notice() { return <motion.section className="notice-wrap" variants={reveal} initial="hidden" whileInView="show" viewport={{ once: true, amount: .25 }}><div className="notice"><span className="notice-icon" aria-hidden="true">ℹ️</span><div><h2>IMPORTANT NOTICE</h2><p>The fabrics displayed in this catalogue are for <strong>Reference Only</strong>.</p><p>As <strong>Market Designs Change Frequently</strong>, the exact same design shown in the catalogue may not always be available.</p><p>All orders are strictly <strong>Make To Order</strong>.</p><p>We manufacture premium kurtas according to your selected fabric (subject to availability) and your required <strong>Custom Size</strong>.</p><p>Our team will always share the <strong>Latest Available Fabric</strong> options before confirming your order.</p></div></div></motion.section> }

function Collections() { const [lightbox, setLightbox] = useState(-1); return <motion.section id="collections" className="collections section" variants={stagger} initial="hidden" whileInView="show" viewport={{ once: true, amount: .01 }}><motion.div className="gallery-heading" variants={reveal}><p className="eyebrow">PREMIUM GALLERY</p><h2>Our Fabric Collection</h2><p>Browse our latest premium kurta fabrics.</p></motion.div><motion.div className="fabric-gallery" variants={stagger}>{fabricGallery.map((image, index) => <motion.button variants={reveal} className="fabric-gallery-card reset" onClick={() => setLightbox(index)} key={image} whileHover={{ y: -7, scale: 1.015 }} whileTap={{ scale: .99 }}><img src={image} alt={`Premium kurta fabric ${index + 1}`} loading="lazy" /></motion.button>)}</motion.div><Lightbox open={lightbox >= 0} close={() => setLightbox(-1)} index={lightbox} slides={fabricGallery.map((src) => ({ src }))} plugins={[Zoom]} animation={{ fade: 420, swipe: 500, zoom: 450 }} zoom={{ maxZoomPixelRatio: 3, scrollToZoom: true }} /></motion.section> }

function Journey() { const [video, setVideo] = useState(null); return <motion.section id="market-journey" className="journey section" variants={stagger} initial="hidden" whileInView="show" viewport={{ once: true, amount: .1 }}><motion.div className="section-heading journey-heading" variants={reveal}><div><p className="eyebrow">MARKET JOURNEY</p><h2>Close to the<br /><em>craft.</em></h2></div><p>A visual record of the market, material selection, and the people behind every collection.</p></motion.div><motion.div className="masonry" variants={stagger}>{galleryImages.map((item) => <motion.article variants={reveal} className={`journey-card ${item.size}`} key={item.title}><img src={item.image} alt={item.title} loading="lazy" /><h3>{item.title}</h3></motion.article>)}{videos.map((item) => <motion.article variants={reveal} whileHover={{ scale: 1.02 }} className="journey-card video-card" key={item.title}><video src={item.url} muted autoPlay loop playsInline preload="metadata" className="journey-video" /><motion.button whileHover={{ scale: 1.12 }} whileTap={{ scale: .92 }} onClick={() => setVideo(item)} aria-label={`Play ${item.title}`}><FiPlay /></motion.button><h3>{item.title}</h3></motion.article>)}</motion.div><VideoModal video={video} onClose={() => setVideo(null)} /></motion.section> }


function Contact() { return <motion.section id="contact" className="contact" variants={reveal} initial="hidden" whileInView="show" viewport={{ once: true, amount: .25 }}><div><p className="eyebrow">CONTACT</p><h2>Find the fabric<br /><em>that fits.</em></h2></div><div className="contact-links"><p>For catalogue enquiries and wholesale kurta fabric sourcing, speak with VESTIORA.</p><a className="contact-phone" href={call}>{phone} <FiArrowUpRight /></a><div><motion.a className="button light" href={call} whileHover={{ y: -3, scale: 1.02 }} whileTap={{ scale: .97 }}><FiPhone /> Call VESTIORA</motion.a><motion.a className="button outline" href={whatsapp} target="_blank" rel="noreferrer" whileHover={{ y: -3, scale: 1.02 }} whileTap={{ scale: .97 }}><FaWhatsapp /> WhatsApp</motion.a></div></div></motion.section> }
function Footer() { return <motion.footer initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: .6 }}><motion.img src={logo} alt="VESTIORA" style={{ height: '45px', width: 'auto', display: 'block' }} whileHover={{ scale: 1.035 }} /><span>© 2026 All Rights Reserved.</span></motion.footer> }
function AppContent() { useEffect(() => { document.title = 'VESTIORA | Premium Kurta Fabric Catalogue' }, []); const home = () => setTimeout(() => go('home'), 0); return <><ScrollProgress /><Nav onHome={home} /><motion.main key="home" initial={{ opacity: 0, y: 18, scale: .995, filter: 'blur(6px)' }} animate={{ opacity: 1, y: 0, scale: 1, filter: 'blur(0px)' }} transition={{ duration: .68, ease: [0.22, 1, 0.36, 1] }}><Hero /><Notice /><Collections /><Journey /><Contact /></motion.main><motion.a className="whatsapp" href={whatsapp} target="_blank" rel="noreferrer" aria-label="WhatsApp VESTIORA" whileHover={{ scale: 1.1, y: -3 }} whileTap={{ scale: .93 }}><FaWhatsapp /></motion.a><Footer /></> }
export default function CatalogPage() { return <><Preloader /><AppContent /></> }
